name: Deploy Application

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Create configuration file(s)
        run: |
          # Write the environment variables directly to file without shell interpretation
          cat << 'EOF' > .env
          ${{ vars.ENV }}
          EOF

      - name: Install SSH keys
        # check this thread to understand why its needed:
        # https://stackoverflow.com/a/70447517
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Upload configuration file(s)
        run: |
          rsync -azlh --delete .env ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}

      - name: Build & Restart Service
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
          cd ${{ secrets.DEPLOY_PATH }}
          [ -d "${{ secrets.DEPLOY_PATH }}/packages/client-twitter/dist" ] && rm -rf "${{ secrets.DEPLOY_PATH }}/packages/client-twitter/dist"
          [ -d "${{ secrets.DEPLOY_PATH }}/packages/plugin-d.a.t.a/dist" ] && rm -rf "${{ secrets.DEPLOY_PATH }}/packages/plugin-d.a.t.a/dist"
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          nvm use
          pnpm build
          sudo systemctl restart ${{ secrets.SERVICE_FILE }}
          EOF
